# Generated by Django 5.2.4 on 2025-07-29 08:05

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(default='standard', max_length=50)),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to=reports.models.lab_upload_path)),
                ('footer_text', models.TextField(blank=True, default='This report is electronically generated and signed.')),
                ('is_default', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='accounts.lab')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('HEADER', 'Header'), ('PATIENT_INFO', 'Patient Information'), ('TEST_RESULTS', 'Test Results'), ('INTERPRETATION', 'Clinical Interpretation'), ('FOOTER', 'Footer')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content_template', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_sections', to='accounts.lab')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('report_format', models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML')], default='PDF', max_length=10)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('DELIVERED', 'Delivered')], default='DRAFT', max_length=20)),
                ('is_confidential', models.BooleanField(default=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_reports', to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(to='tests.test')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['-generated_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(fields=('lab', 'name'), name='uniq_reporttemplate_name_per_lab'),
        ),
        migrations.AddConstraint(
            model_name='reportsection',
            constraint=models.UniqueConstraint(fields=('lab', 'template', 'section_type'), name='uniq_section_type_per_template_per_lab'),
        ),
    ]
