# Generated by Django 5.2.4 on 2025-07-24 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_file', models.FileField(upload_to='report_templates/')),
                ('is_default', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('report_format', models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML'), ('EXCEL', 'Excel')], default='PDF', max_length=10)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('DELIVERED', 'Delivered')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_reports', to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(to='tests.test')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['-generated_date'],
            },
        ),
    ]
