# Generated by Django 5.2.4 on 2025-07-24 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttemplate',
            name='template_file',
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='footer_text',
            field=models.TextField(blank=True, default='This report is electronically generated and signed.'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to='report_templates/logos/'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='template_type',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML')], default='PDF', max_length=10),
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('HEADER', 'Header'), ('PATIENT_INFO', 'Patient Information'), ('TEST_RESULTS', 'Test Results'), ('INTERPRETATION', 'Clinical Interpretation'), ('FOOTER', 'Footer')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content_template', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'section_type')},
            },
        ),
    ]
