# Generated by Django 5.2.4 on 2025-07-26 08:14

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reports', '0002_remove_reporttemplate_template_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportsection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='report',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.lab'),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_sections', to='accounts.lab'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='accounts.lab'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=reports.models.lab_upload_path),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to=reports.models.lab_upload_path),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='reportsection',
            constraint=models.UniqueConstraint(fields=('lab', 'template', 'section_type'), name='uniq_section_type_per_template_per_lab'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(fields=('lab', 'name'), name='uniq_reporttemplate_name_per_lab'),
        ),
    ]
