# Generated by Django 5.2.4 on 2025-07-26 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='accounts.lab'),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_categories', to='accounts.lab'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='accounts.lab'),
        ),
        migrations.AddField(
            model_name='testtype',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_types', to='accounts.lab'),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='testcategory',
            constraint=models.UniqueConstraint(fields=('lab', 'name'), name='uniq_testcategory_name_per_lab'),
        ),
        migrations.AddConstraint(
            model_name='testcategory',
            constraint=models.UniqueConstraint(fields=('lab', 'code'), name='uniq_testcategory_code_per_lab'),
        ),
        migrations.AddConstraint(
            model_name='testtype',
            constraint=models.UniqueConstraint(fields=('lab', 'code'), name='uniq_testtype_code_per_lab'),
        ),
        migrations.AddConstraint(
            model_name='testtype',
            constraint=models.UniqueConstraint(fields=('lab', 'name'), name='uniq_testtype_name_per_lab'),
        ),
    ]
